<?php

namespace CustomerBundle\Repository;

/**
 * CustomerCommunicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerCommunicationRepository extends \Doctrine\ORM\EntityRepository
{
}
